-- 배관 꺾임특징점(Bend Feature Point) 스키마.
-- 설계 근거: Docs/BendFeaturePoint_Development_Plan.md 8절.
-- TB_ROUTE_BEND_FEATURE_POINT: 경로 단위 개별 꺾임점 인스턴스 (매 build마다 대상 경로 전량 재계산/재적재).
-- TB_ROUTE_BEND_FEATURE_PATTERN: 구조적 키로 그룹핑한 빈도 집계 템플릿 (v1.1은 전체 build, SOURCE_HASH는 provenance용).

CREATE TABLE IF NOT EXISTS "TB_ROUTE_BEND_FEATURE_POINT" (
    "BEND_ID" bigserial PRIMARY KEY,
    "PROJECT_SCOPE_KEY" text NOT NULL,
    "MODEL_REVISION_KEY" text NOT NULL,
    "ROUTE_PATH_GUID" text NOT NULL,
    "EQUIPMENT_KEY" text NOT NULL,
    "UTILITY_GROUP" text NOT NULL,
    "UTILITY" text NOT NULL,
    "ORDINAL_FROM_START" integer NOT NULL,
    "ORDINAL_FROM_END" integer NOT NULL,
    "SEGMENT_ZONE" text NOT NULL CHECK ("SEGMENT_ZONE" IN ('START_STUB', 'MIDDLE_TRUNK', 'END_STUB')),
    "REL_POSITION_BUCKET" numeric(3, 2) NOT NULL,
    "TRANSITION_TYPE" text NOT NULL CHECK ("TRANSITION_TYPE" IN ('V_TO_H', 'H_TO_V', 'H_TO_H', 'V_TO_V')),
    "AXIS_BEFORE" text NOT NULL,
    "AXIS_AFTER" text NOT NULL,
    "CAUSE" text NOT NULL CHECK ("CAUSE" IN ('OBSTACLE_AVOID', 'DESTINATION_ENTRY', 'ZONE_CONSTRAINT', 'GROUP_ALIGNMENT', 'UNKNOWN')),
    "CAUSE_EVIDENCE" jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof("CAUSE_EVIDENCE") = 'object'),
    "IS_ELBOW_RESTORED_IP" boolean NOT NULL DEFAULT false,
    "IP_RESTORE_SKEW_DIST_MM" double precision,
    "ANCHOR_REL_POSITION" jsonb CHECK ("ANCHOR_REL_POSITION" IS NULL OR jsonb_typeof("ANCHOR_REL_POSITION") = 'array'),
    "IS_HORIZONTAL_SEQUENCE" boolean NOT NULL DEFAULT false,
    "POINT_3D" geometry(PointZ, 0) NOT NULL,
    "BUILD_RUN_ID" uuid NOT NULL,
    "CREATED_AT" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_TRBFP_POINT_3D" ON "TB_ROUTE_BEND_FEATURE_POINT" USING GIST ("POINT_3D");
CREATE INDEX IF NOT EXISTS "IX_TRBFP_GROUP_KEY" ON "TB_ROUTE_BEND_FEATURE_POINT" ("EQUIPMENT_KEY", "UTILITY_GROUP", "UTILITY", "TRANSITION_TYPE");
CREATE INDEX IF NOT EXISTS "IX_TRBFP_ROUTE_GUID" ON "TB_ROUTE_BEND_FEATURE_POINT" ("ROUTE_PATH_GUID");

COMMENT ON TABLE "TB_ROUTE_BEND_FEATURE_POINT" IS '경로 단위 개별 꺾임특징점. IP 복원 및 재세그멘테이션을 거친 폴리라인에서 추출한 원자료.';
COMMENT ON COLUMN "TB_ROUTE_BEND_FEATURE_POINT"."IS_ELBOW_RESTORED_IP" IS 'true면 이 좌표는 실측점이 아니라 전후 직관을 연장한 가상 교차점(IP)이다.';
COMMENT ON COLUMN "TB_ROUTE_BEND_FEATURE_POINT"."IP_RESTORE_SKEW_DIST_MM" IS 'IP 복원 시 두 직선이 완전히 교차하지 않고 벌어져 있던 거리(mm). IS_ELBOW_RESTORED_IP=false면 NULL.';

CREATE TABLE IF NOT EXISTS "TB_ROUTE_BEND_FEATURE_PATTERN" (
    "PATTERN_ID" text PRIMARY KEY,
    "PROJECT_SCOPE_KEY" text NOT NULL,
    "MODEL_REVISION_KEY" text NOT NULL,
    "EQUIPMENT_KEY" text NOT NULL,
    "UTILITY_GROUP" text NOT NULL,
    "UTILITY" text NOT NULL,
    "TRANSITION_TYPE" text NOT NULL,
    "SEGMENT_ZONE" text NOT NULL,
    "REL_POSITION_BUCKET" numeric(3, 2) NOT NULL,
    "SAMPLE_COUNT" integer NOT NULL CHECK ("SAMPLE_COUNT" >= 1),
    "BEND_INSTANCE_COUNT" integer NOT NULL CHECK ("BEND_INSTANCE_COUNT" >= "SAMPLE_COUNT"),
    "TOTAL_ROUTES_IN_SCOPE" integer NOT NULL,
    "FREQUENCY_SCORE" double precision NOT NULL CHECK ("FREQUENCY_SCORE" BETWEEN 0 AND 1),
    "DOMINANT_CAUSE" text NOT NULL,
    "CAUSE_CONFIDENCE" double precision NOT NULL CHECK ("CAUSE_CONFIDENCE" BETWEEN 0 AND 1),
    "CAUSE_BREAKDOWN" jsonb NOT NULL CHECK (jsonb_typeof("CAUSE_BREAKDOWN") = 'object'),
    "POSITION_CONSISTENCY" double precision,
    "REPRESENTATIVE_POINT" geometry(PointZ, 0),
    "AVG_POSITION" geometry(PointZ, 0),
    "POSITION_STD_MM" double precision,
    "AVG_ANCHOR_REL_POSITION" jsonb CHECK ("AVG_ANCHOR_REL_POSITION" IS NULL OR jsonb_typeof("AVG_ANCHOR_REL_POSITION") = 'array'),
    "ANCHOR_REL_STD" double precision,
    "MEMBER_BEND_IDS" jsonb NOT NULL CHECK (jsonb_typeof("MEMBER_BEND_IDS") = 'array'),
    "SOURCE_HASH" text NOT NULL,
    "BUILD_RUN_ID" uuid NOT NULL,
    "CREATED_AT" timestamptz NOT NULL DEFAULT now(),
    "UPDATED_AT" timestamptz NOT NULL DEFAULT now()
);

-- 기존 v1 테이블에도 안전하게 신규 정확도 컬럼을 추가한다.
ALTER TABLE "TB_ROUTE_BEND_FEATURE_POINT"
    ADD COLUMN IF NOT EXISTS "ANCHOR_REL_POSITION" jsonb,
    ADD COLUMN IF NOT EXISTS "IS_HORIZONTAL_SEQUENCE" boolean NOT NULL DEFAULT false;
ALTER TABLE "TB_ROUTE_BEND_FEATURE_PATTERN"
    ADD COLUMN IF NOT EXISTS "BEND_INSTANCE_COUNT" integer,
    ADD COLUMN IF NOT EXISTS "AVG_ANCHOR_REL_POSITION" jsonb,
    ADD COLUMN IF NOT EXISTS "ANCHOR_REL_STD" double precision;
UPDATE "TB_ROUTE_BEND_FEATURE_PATTERN"
SET "BEND_INSTANCE_COUNT" = "SAMPLE_COUNT"
WHERE "BEND_INSTANCE_COUNT" IS NULL;
ALTER TABLE "TB_ROUTE_BEND_FEATURE_PATTERN"
    ALTER COLUMN "BEND_INSTANCE_COUNT" SET NOT NULL;

-- v1.2: Top-K UtilityPipeGroup 검색과 후보를 join하려면 ROUTE_PATH_GUID만으로는 scope를
-- 구분할 수 없다 (TB_ROUTE_FEATURE_VECTOR/TB_ROUTE_UTILITY_GROUP_VECTOR와 동일한 이유).
-- 기존 v1/v1.1 DB에도 컬럼을 추가하되, 과거 행은 build 재실행 전까지 scope를 알 수 없으므로
-- 빈 문자열로 채워 NOT NULL을 만족시키고 다음 build에서 정상 값으로 재적재되도록 한다.
ALTER TABLE "TB_ROUTE_BEND_FEATURE_POINT"
    ADD COLUMN IF NOT EXISTS "PROJECT_SCOPE_KEY" text,
    ADD COLUMN IF NOT EXISTS "MODEL_REVISION_KEY" text;
UPDATE "TB_ROUTE_BEND_FEATURE_POINT" SET "PROJECT_SCOPE_KEY" = '' WHERE "PROJECT_SCOPE_KEY" IS NULL;
UPDATE "TB_ROUTE_BEND_FEATURE_POINT" SET "MODEL_REVISION_KEY" = '' WHERE "MODEL_REVISION_KEY" IS NULL;
ALTER TABLE "TB_ROUTE_BEND_FEATURE_POINT"
    ALTER COLUMN "PROJECT_SCOPE_KEY" SET NOT NULL,
    ALTER COLUMN "MODEL_REVISION_KEY" SET NOT NULL;

-- 이 인덱스는 위에서 PROJECT_SCOPE_KEY/MODEL_REVISION_KEY 컬럼이 신규 설치든 기존 DB
-- 마이그레이션이든 확실히 존재하게 된 뒤에 만들어야 한다(순서를 앞으로 옮기면 기존 v1/v1.1
-- DB에서 컬럼이 아직 없는 시점에 CREATE INDEX가 실행되어 UndefinedColumn 오류가 난다).
CREATE INDEX IF NOT EXISTS "IX_TRBFP_SCOPE" ON "TB_ROUTE_BEND_FEATURE_POINT" ("PROJECT_SCOPE_KEY", "MODEL_REVISION_KEY");

ALTER TABLE "TB_ROUTE_BEND_FEATURE_PATTERN"
    ADD COLUMN IF NOT EXISTS "PROJECT_SCOPE_KEY" text,
    ADD COLUMN IF NOT EXISTS "MODEL_REVISION_KEY" text;
UPDATE "TB_ROUTE_BEND_FEATURE_PATTERN" SET "PROJECT_SCOPE_KEY" = '' WHERE "PROJECT_SCOPE_KEY" IS NULL;
UPDATE "TB_ROUTE_BEND_FEATURE_PATTERN" SET "MODEL_REVISION_KEY" = '' WHERE "MODEL_REVISION_KEY" IS NULL;
ALTER TABLE "TB_ROUTE_BEND_FEATURE_PATTERN"
    ALTER COLUMN "PROJECT_SCOPE_KEY" SET NOT NULL,
    ALTER COLUMN "MODEL_REVISION_KEY" SET NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_TRBFPT_REP_POINT" ON "TB_ROUTE_BEND_FEATURE_PATTERN" USING GIST ("REPRESENTATIVE_POINT");
CREATE INDEX IF NOT EXISTS "IX_TRBFPT_GROUP_KEY" ON "TB_ROUTE_BEND_FEATURE_PATTERN" ("EQUIPMENT_KEY", "UTILITY_GROUP", "UTILITY");
CREATE INDEX IF NOT EXISTS "IX_TRBFPT_SCOPE" ON "TB_ROUTE_BEND_FEATURE_PATTERN" ("PROJECT_SCOPE_KEY", "MODEL_REVISION_KEY");

COMMENT ON TABLE "TB_ROUTE_BEND_FEATURE_PATTERN" IS '구조적 키(장비/유틸리티/전환유형/구간/상대위치) 기준 빈도 집계 템플릿. min-samples 이상 반복된 그룹만 승격.';
COMMENT ON COLUMN "TB_ROUTE_BEND_FEATURE_PATTERN"."FREQUENCY_SCORE" IS 'SAMPLE_COUNT / TOTAL_ROUTES_IN_SCOPE. 이 조합에서 몇 %의 경로가 이 꺾임을 갖는가.';
COMMENT ON COLUMN "TB_ROUTE_BEND_FEATURE_PATTERN"."CAUSE_CONFIDENCE" IS '다수결 원인(DOMINANT_CAUSE)이 차지하는 비율.';
