-- Context Vector 실제 라우팅 A/B 결과 로그.
-- 업무 원본 테이블과 분리된 관찰 전용 append-only 테이블이다.

CREATE TABLE IF NOT EXISTS "TB_CONTEXT_ROUTING_AB_LOG" (
    "LOG_ID" uuid PRIMARY KEY,
    "RUN_ID" uuid NOT NULL,
    "EXPERIMENT_ID" text NOT NULL,
    "REQUEST_KEY" char(64) NOT NULL,
    "ARM" text NOT NULL CHECK ("ARM" IN ('BASELINE_TOPK', 'CONTEXT_V3', 'NO_TOPK')),
    "IS_SHADOW" boolean NOT NULL DEFAULT false,
    "PROJECT_KEY" text,
    "MODEL_REVISION_KEY" text,
    "ROUTE_PATH_GUID" text,
    "EQUIPMENT_NAME" text,
    "UTILITY_GROUP" text,
    "UTILITY" text,
    "SOURCE_X" double precision NOT NULL,
    "SOURCE_Y" double precision NOT NULL,
    "SOURCE_Z" double precision NOT NULL,
    "TARGET_X" double precision NOT NULL,
    "TARGET_Y" double precision NOT NULL,
    "TARGET_Z" double precision NOT NULL,
    "DIAMETER_MM" double precision,
    "TOPK_ROUTE_GUIDS" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "TOPK_SEARCH_MS" double precision,
    "CONTEXT_COVERAGE" double precision,
    "CONTEXT_FALLBACK_COUNT" integer,
    "RERANK_WEIGHT_PROFILE" text,
    "CONTEXT_SNAPSHOT_HASH" text,
    "CONTEXT_SCOPE_STATUS" text,
    "CONTEXT_BUILD_RUN_ID" text,
    "CONTEXT_PROJECT_SCOPE_KEY" text,
    "CONTEXT_MODEL_REVISION_KEY" text,
    "CONTEXT_ENCODER_VERSION" text,
    "CONTEXT_ENCODER_CONFIG_HASH" text,
    "CONTEXT_PROVENANCE_CONSISTENT" boolean NOT NULL DEFAULT true,
    "CONTEXT_PROVENANCE_ISSUE" text,
    "CORRIDOR_POLICY" text NOT NULL DEFAULT 'union',
    "CORRIDOR_RANK_PROFILE" text,
    "CORRIDOR_COST_FACTOR" double precision NOT NULL DEFAULT 0.5,
    "CORRIDOR_CELL_COUNT" integer NOT NULL DEFAULT 0,
    "CORRIDOR_EXCLUSIVE_CELL_COUNT" integer NOT NULL DEFAULT 0,
    "ENDPOINT_RELEASE_COUNT" integer NOT NULL DEFAULT 0,
    "ROUTE_SUCCESS" boolean NOT NULL,
    "ROUTE_FAIL_REASON" text,
    "ROUTE_LENGTH_MM" double precision,
    "ROUTE_BEND_COUNT" integer,
    "COLLISION_COUNT" integer,
    "EXPANDED_NODES" bigint,
    "ROUTE_ELAPSED_MS" double precision,
    "CREATED_AT" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "TB_CONTEXT_ROUTING_AB_LOG"
    ADD COLUMN IF NOT EXISTS "PROJECT_KEY" text;
ALTER TABLE "TB_CONTEXT_ROUTING_AB_LOG"
    ADD COLUMN IF NOT EXISTS "MODEL_REVISION_KEY" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_SNAPSHOT_HASH" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_SCOPE_STATUS" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_BUILD_RUN_ID" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_PROJECT_SCOPE_KEY" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_MODEL_REVISION_KEY" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_ENCODER_VERSION" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_ENCODER_CONFIG_HASH" text,
    ADD COLUMN IF NOT EXISTS "CONTEXT_PROVENANCE_CONSISTENT" boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS "CONTEXT_PROVENANCE_ISSUE" text,
    ADD COLUMN IF NOT EXISTS "CORRIDOR_POLICY" text NOT NULL DEFAULT 'union',
    ADD COLUMN IF NOT EXISTS "CORRIDOR_RANK_PROFILE" text,
    ADD COLUMN IF NOT EXISTS "CORRIDOR_COST_FACTOR" double precision NOT NULL DEFAULT 0.5,
    ADD COLUMN IF NOT EXISTS "CORRIDOR_CELL_COUNT" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "CORRIDOR_EXCLUSIVE_CELL_COUNT" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "ENDPOINT_RELEASE_COUNT" integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "IX_CONTEXT_ROUTING_AB_REQUEST_ARM"
    ON "TB_CONTEXT_ROUTING_AB_LOG" ("EXPERIMENT_ID", "REQUEST_KEY", "ARM", "CREATED_AT" DESC);
CREATE INDEX IF NOT EXISTS "IX_CONTEXT_ROUTING_AB_RUN"
    ON "TB_CONTEXT_ROUTING_AB_LOG" ("RUN_ID");
CREATE INDEX IF NOT EXISTS "IX_CONTEXT_ROUTING_AB_SNAPSHOT"
    ON "TB_CONTEXT_ROUTING_AB_LOG" ("CONTEXT_SNAPSHOT_HASH", "CONTEXT_SCOPE_STATUS", "CREATED_AT" DESC);

COMMENT ON TABLE "TB_CONTEXT_ROUTING_AB_LOG" IS
    'Context Vector baseline/context 실제 라우팅 결과를 동일 REQUEST_KEY로 비교하는 append-only A/B 로그';
