CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS "TB_ROUTE_PATH_SEGMENTATION" CASCADE;

CREATE TABLE IF NOT EXISTS "TB_ROUTE_PATH_SEGMENTATION" (
    "ROUTE_PATH_GUID" text PRIMARY KEY,
    "START_STUB_GEOM" geometry(LineStringZ, 0),
    "MIDDLE_TRUNK_GEOM" geometry(LineStringZ, 0),
    "END_STUB_GEOM" geometry(LineStringZ, 0),
    "START_FREE_POINT" geometry(PointZ, 0),
    "END_FREE_POINT" geometry(PointZ, 0),
    "CREATED_AT" timestamp without time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_TRPS_START_STUB" ON "TB_ROUTE_PATH_SEGMENTATION" USING gist("START_STUB_GEOM");
CREATE INDEX IF NOT EXISTS "IX_TRPS_MIDDLE_TRUNK" ON "TB_ROUTE_PATH_SEGMENTATION" USING gist("MIDDLE_TRUNK_GEOM");
CREATE INDEX IF NOT EXISTS "IX_TRPS_END_STUB" ON "TB_ROUTE_PATH_SEGMENTATION" USING gist("END_STUB_GEOM");
